#! /bin/sh

#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

xrdb merge ~/.Xresources &

pgrep -x picom > /dev/null || picom --experimental-backends &

pgrep -x polkit-mate-authentication-agent-1 > /dev/null || /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
pgrep -x ibus-daemon > /dev/null || ibus-daemon -drx &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x blueman-applet > /dev/null || blueman-applet &
pgrep -x kdeconnect-indicator > /dev/null || kdeconnect-indicator &
pgrep -x xscreensaver > /dev/null || xscreensaver -no-splash &
pgrep -x ntfd > /dev/null || ntfd &
pgrep -x xpad > /dev/null || xpad -N &
pgrep -f telegram-desktop > /dev/null || QT_IM_MODULE=ibus telegram-desktop -startintray &
pgrep -f cadence > /dev/null || cadence --minimized &
pgrep -f 1password > /dev/null || 1password --silent &

feh --bg-fill ~/Pictures/wallpaper-37.png


# workspaces 
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DisplayPort-1 -d 6 7 8 9 0

#bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config top_padding 0
bspc config bottom_padding -24

# borders
bspc config border_width 0
bspc config normal_border_color "#444444"
bspc config focused_border_color "#bbc5ff"

#gaps 
bspc config gapless_monocle false
bspc config window_gap 30
bspc config split_ratio 0.50

# float
bspc rule -a TelegramDesktop state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a lazarus state=floating
bspc rule -a fontforge state=floating
bspc rule -a obs state=floating
bspc rule -a UE4Editor state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a xpad state=floating
bspc rule -a GitHub\ Desktop state=floating
bspc rule -a Screenkey manage=off
bspc rule -a 1Password state=floating

~/.config/scripts/redshift-ctrl night
~/.config/polybar/launch.sh &

