#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--me" ]]; then
	close_dash && microsoft-edge-stable &

elif [[ "$1" == "--tg" ]]; then
	close_dash && telegram-desktop &

elif [[ "$1" == "--1p" ]]; then
	close_dash && 1password &

elif [[ "$1" == "--tr" ]]; then
	close_dash && alacritty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--vm" ]]; then
	close_dash && virt-manager &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--ki" ]]; then
	close_dash && krita &

elif [[ "$1" == "--uh" ]]; then
	close_dash && unityhub &

fi
