#!/bin/bash
MF=/tmp/grayscale_now
STATUS=`cat $MF`

WALLPAPER_COLOR=~/Pictures/wallpaper/forest.png
WALLPAPER_BW=~/Pictures/wallpaper/forest_bw.png

if [ "$1" = 'toggle' ]; then
  GRAYSCALE_SHADER='uniform sampler2D tex; uniform float opacity; void main() { vec4 c = texture2D(tex, gl_TexCoord[0].xy); float y = dot(c.rgb, vec3(0.2126, 0.7152, 0.0722)); gl_FragColor = opacity*vec4(y, y, y, c.a); }'
  rm -rf $MF
  if [ "$STATUS" = 'grayscale' ]; then
    echo color > $MF
    killall -9 picom
    feh --bg-fill $WALLPAPER_COLOR
    sleep .5
    picom &
  else
    echo grayscale > $MF
    killall -9 picom
    sleep .5
    picom --glx-fshader-win "${GRAYSCALE_SHADER}" &
    feh --bg-fill $WALLPAPER_BW
  fi
else
  if [ "$STATUS" = 'grayscale' ]; then
    echo GRAYSCALE
  else
    echo COLOR
  fi
fi
