#!/bin/bash

if [ "$1" = 'mount' ]; then
	pgrep -f OneDrive > /dev/null || rclone --vfs-cache-mode writes mount onedrive: ~/OneDrive &
elif [ "$1" = 'unmount' ]; then
	umount ~/OneDrive
elif [ "$1" = 'toggle' ]; then
	ST=`pgrep -f OneDrive | wc -l`
	if [ $ST -eq 0 ]; then
		pgrep -f OneDrive > /dev/null || rclone --vfs-cache-mode writes mount onedrive: ~/OneDrive &
	else
		umount ~/OneDrive
	fi
elif [ "$1" = 'status' ]; then
	MOUNT=`pgrep -f OneDrive | wc -l`
	if [ $MOUNT -eq 0 ]; then
		echo 
	else
		echo 
	fi
fi

