#!/bin/bash
SELF=`dirname "$0"`
POWER=`${SELF}/power-status`
if [ $POWER = 'on-line' ]; then
	UPDATES=`checkupdates | wc -l`
  if [ "$UPDATES" -eq "0" ]; then
    echo ""
  else
    echo "UPDATES:$UPDATES"
  fi
else
	echo ""
fi
